name: "Example Workflow Using Reusable Action"

on:
  push:
    branches:
      - main

jobs:
  notify_to_lark:
    name: Notify to Lark
    runs-on: ubuntu-latest
    outputs:
      version_info: ${{ steps.meta.outputs.version_info }}
      commit_logs: ${{ steps.meta.outputs.commit_logs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get Github version info"
        id: meta
        run: |
          commit_id=`echo ${GITHUB_SHA} | cut -c1-8`
          repository_url=${{ github.event.repository.html_url }}
          version_info="[${{ github.ref_name }}](${repository_url}/tree/${{ github.ref_name }}) (commit=[${commit_id}](${repository_url}/commit/${{ github.sha }}))"
          echo "version_info=$version_info" >> $GITHUB_OUTPUT

          commit_logs=$(git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:"%h(%an) - %s")
          echo "commit_logs=$commit_logs" >> $GITHUB_OUTPUT
        continue-on-error: true


  greet:
    runs-on: ubuntu-latest
    needs: notify_to_lark
    steps:
      - name: Use My Custom Action
        run: |
          echo "version_info: ${{ needs.notify_to_lark.outputs.version_info }}"
          echo "commit_logs: ${{ needs.notify_to_lark.outputs.commit_logs }}"
