name: "Example Workflow Using Reusable Action"

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Use My Custom Action
        run: |
          echo "url: ${{ github.event.repository.html_url }}"
