name: ci-diff-test

on:
  push:
    branches:
    - 'main'

jobs:
  diff_test:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/get-diff-action@v6.1.2
      id: git_diff
      with:
        PATTERNS: |
          **/**.go
          go.mod
          go.sum