name: Build and Deploy Mechain

on:
  push:
    branches:
      - 'main'

jobs:
  publish_image:
    name: Publish Docker image
    uses: './.github/workflows/docker-publish.yaml'
    secrets: inherit
    with:
      tags: kevin2025/action-test:develop
