name: Build and Deploy Mechain

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: show info
        run: whereis docker
      - name: login to docker hub
        run: docker login ${{secrets.DOCKER_REPOSITORY}} -u ${{secrets.DOCKER_USERNAME}} -p "{{secrets.DOCKER_PASSWORD}}"

